server:
  port: 8092

spring:
  application:
    name: historial
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false

  datasource:
    url: jdbc:postgresql://localhost:5432/historial
    username: postgres
    password: 265359


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka